# Sample .travis.yml for R projects.

language: c

# To build on OSX, switch the previous line to
# language: objective-c
script: ./travis-tool.sh run_tests

before_install:
    - cd $REPO_TO_TEST
    - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
    - chmod 755 ./travis-tool.sh
    - ./travis-tool.sh bootstrap
install:
    - ./travis-tool.sh install_deps
    - ./travis-tool.sh github_package assertthat

# Configuration options below this line are suggested options.
notifications:
    email:
    on_success: change
    on_failure: change

env:
  matrix:
        - REPO_TO_TEST=badpackage
        - REPO_TO_TEST=goodpackage

