language: java
script: ./travis-tool.sh run_tests

before_install:
    - pwd
    - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
    - chmod 755 ./travis-tool.sh
    - ./travis-tool.sh bootstrap
install:
    - pwd
    - R CMD javareconf
    - ./travis-tool.sh install_deps

